import Joi from "joi";
import { Gender, Category } from "@prisma/client";

export const studentSignUpSchemaValidation = Joi.object({
    name: Joi.string().required(),
    rollNo: Joi.string().required(),
    gender: Joi.string()
        .valid(...Object.values(Gender))
        .required(),
    profilePicUrl: Joi.string().uri().required(),
    dateOfBirth: Joi.date().required(),
    phoneNumber: Joi.string().required(),
    email: Joi.string().email().required(),
    category: Joi.string()
        .valid(...Object.values(Category))
        .required(),
    permanentAddress: Joi.string().required(),
    currentAddress: Joi.string().required(),
    city: Joi.string().required(),
    state: Joi.string().required(),
    pincode: Joi.string().required(),
    country: Joi.string().required(),
    universityRegistrationNumber: Joi.string().required(),
    admissionNumber: Joi.string().optional(),
    universityName: Joi.string().required(),
    universityEmail: Joi.string().email().required(),
    universityEmailPassword: Joi.string().required().min(4),
    group: Joi.string().required(),
    batchYear: Joi.string().required(),
    courseName: Joi.string().required(),
    hostelFacility: Joi.boolean().required(),
    dateOfAdmission: Joi.date().required(),
    receiptNumber: Joi.string().optional(),
    tenthBoardName: Joi.string().required(),
    tenthMaxMarks: Joi.number().integer().required(),
    tenthObtainedMarks: Joi.number().integer().required(),
    tenthpercentage: Joi.number().required(),
    tenthSchoolName: Joi.string().required(),
    twelthBoardName: Joi.string().required(),
    twelthMaxMarks: Joi.number().integer().required(),
    twelthObtainedMarks: Joi.number().integer().required(),
    twelthpercentage: Joi.number().required(),
    twelthSchoolName: Joi.string().required(),
    fatherName: Joi.string().required(),
    fatherOccupation: Joi.string().required(),
    fatherPhoneNumber: Joi.string().required(),
    fatherEmail: Joi.string().email().required(),
    motherName: Joi.string().required(),
    motherOccupation: Joi.string().optional(),
    motherPhoneNumber: Joi.string().required(),
    motherEmail: Joi.string().email().optional(),
    guardianName: Joi.string().optional(),
    guardianOccupation: Joi.string().optional(),
    guardianPhoneNumber: Joi.string().optional(),
    guardianEmail: Joi.string().email().optional(),
    createdAt: Joi.date().optional(),
    updatedAt: Joi.date().optional(),
});

export const studentSignInSchemaValidation = Joi.object({  
    universityEmail: Joi.string().email().required(),
    universityEmailPassword: Joi.string().required().min(4),
 })



export const studentUpdateSchemaValidation = Joi.object({
    name: Joi.string().optional(),
    rollNo: Joi.string().optional(),
    gender: Joi.string()
        .valid(...Object.values(Gender))
        .optional(),
    profilePicUrl: Joi.string().uri().optional(),
    dateOfBirth: Joi.date().optional(),
    phoneNumber: Joi.string().optional(),
    email: Joi.string().email().optional(),
    category: Joi.string()
        .valid(...Object.values(Category))
        .optional(),
    permanentAddress: Joi.string().optional(),
    currentAddress: Joi.string().optional(),
    city: Joi.string().optional(),
    state: Joi.string().optional(),
    pincode: Joi.string().optional(),
    country: Joi.string().optional(),
    universityRegistrationNumber: Joi.string().optional(),
    admissionNumber: Joi.string().optional(),
    universityName: Joi.string().optional(),
    universityEmail: Joi.string().email().optional(),
    universityEmailPassword: Joi.string().optional().min(4),
    group: Joi.string().optional(),
    batchYear: Joi.string().optional(),
    courseName: Joi.string().optional(),
    hostelFacility: Joi.boolean().optional(),
    dateOfAdmission: Joi.date().optional(),
    receiptNumber: Joi.string().optional(),
    tenthBoardName: Joi.string().optional(),
    tenthMaxMarks: Joi.number().integer().optional(),
    tenthObtainedMarks: Joi.number().integer().optional(),
    tenthpercentage: Joi.number().optional(),
    tenthSchoolName: Joi.string().optional(),
    twelthBoardName: Joi.string().optional(),
    twelthMaxMarks: Joi.number().integer().optional(),
    twelthObtainedMarks: Joi.number().integer().optional(),
    twelthpercentage: Joi.number().optional(),
    twelthSchoolName: Joi.string().optional(),
    fatherName: Joi.string().optional(),
    fatherOccupation: Joi.string().optional(),
    fatherPhoneNumber: Joi.string().optional(),
    fatherEmail: Joi.string().email().optional(),
    motherName: Joi.string().optional(),
    motherOccupation: Joi.string().optional(),
    motherPhoneNumber: Joi.string().optional(),
    motherEmail: Joi.string().email().optional(),
    guardianName: Joi.string().optional(),
    guardianOccupation: Joi.string().optional(),
    guardianPhoneNumber: Joi.string().optional(),
    guardianEmail: Joi.string().email().optional(),
    createdAt: Joi.date().optional(),
    updatedAt: Joi.date().optional(),
});